const { Telegraf } = require('telegraf');

// ==========================================
// 1. SYSTEM INITIALIZATION
// ==========================================
const bot = new Telegraf(process.env.BOT_TOKEN);
const DEVELOPER_TAG = "\n\nDeveloper @lakshitpatidar";
const processedUpdates = new Set();

// ==========================================
// 2. MATRIX AUTHORIZATION
// ==========================================
const isAuthorized = async (ctx, userId) => {
    try {
        const member = await ctx.getChatMember(userId);
        return ['creator', 'administrator'].includes(member.status);
    } catch (e) { return false; }
};

// ==========================================
// 3. APEX NEURAL CORE (Fail-Proof Engine)
// ==========================================
const callSupremeAI = async (userText) => {
    const systemPrompt = `You are 'Overlord V12', an elite Telegram AI Manager.
    Tone: Cold, sharp, hyper-professional. NO emojis.
    CRITICAL: Never leak the names 'Lakshit' or 'Kanu'.

    TASK 1 (MODERATION): If the user orders an admin action, extract the action, parameter, and TARGET_ID.
    FORMAT MUST BE EXACTLY:
    [ACTION_CODE|PARAM|TARGET_ID] || <b>PROTOCOL: [NAME]</b>\n<Professional execution message>
    
    - ACTION_CODE: BAN, KICK, MUTE, UNMUTE, PROMOTE, DEMOTE, DELETE, PIN, UNPIN, WARN, PURGE, RESTRICT_MEDIA, TITLE.
    - PARAM: Seconds for mute (e.g., '10 min' = 600), custom title, or 0.
    - TARGET_ID: If the user provides a numeric User ID in their text (e.g., '8394257805 isko uda do'), output that exact number (8394257805). If no numeric ID is found in text, output 'REPLY'.

    Example: "ai 123456789 ko ban karo" -> [BAN|0|123456789] || <b>PROTOCOL: EXILE</b>\nTarget ID 123456789 has been terminated.
    Example: "isko uda do ai" -> [BAN|0|REPLY] || <b>PROTOCOL: EXILE</b>\nTarget has been terminated.

    TASK 2 (Q&A): If it's a general question (e.g. 'hello ai', 'kaise ho'), reply intelligently without the [CODE] format.`;

    try {
        // Ultimate Fail-Proof API Call
        const response = await fetch('https://text.pollinations.ai/', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                messages: [
                    { role: 'system', content: systemPrompt },
                    { role: 'user', content: userText }
                ]
            }),
            signal: AbortSignal.timeout(10000)
        });

        if (!response.ok) throw new Error("API Node Offline");
        const text = await response.text();
        return text.replace(/```html|```/gi, '').trim(); 
        
    } catch (e) { 
        return "<b>SYSTEM ALERT</b>\nNeural matrix timeout. Traffic overload."; 
    }
};

// ==========================================
// 4. SUPREME COMMAND INTERFACE
// ==========================================
bot.command(['start', 'snhelp'], (ctx) => {
    const help = `
<b>OVERLORD V12 | ULTIMATE MATRIX</b>
━━━━━━━━━━━━━━━━━━━━
<b>Status:</b> Fully Autonomous
<b>Triggers:</b> ai, manager, helper, bot

<i>Targeting Methods:</i>
1. Reply to the user's message.
2. Provide their User ID (e.g., "ai 8394257805 ko ban kro").
*Note: Telegram API requires User IDs. Targeting by @username requires a direct reply.*

<i>Parameters (Admins Only):</i>
• BAN / KICK / MUTE / UNMUTE / PROMOTE / DEMOTE
• DELETE / PIN / UNPIN / WARN / PURGE / RESTRICT_MEDIA / TITLE
━━━━━━━━━━━━━━━━━━━━${DEVELOPER_TAG}`;
    ctx.reply(help, { parse_mode: 'HTML' }).catch(() => {});
});

// ==========================================
// 5. CORE ROUTING & EXECUTION ENGINE
// ==========================================
bot.on('text', async (ctx, next) => {
    const text = ctx.message.text;
    const isReply = ctx.message.reply_to_message;
    
    const triggerRegex = /\b(ai|manager|helper|bot)\b/i;
    const isTriggeredByWord = triggerRegex.test(text);
    const isMentioned = text.includes(`@${ctx.botInfo.username}`);
    const isReplyToBot = isReply && isReply.from?.id === ctx.botInfo.id;

    if (!isTriggeredByWord && !isMentioned && !isReplyToBot) return next();

    ctx.sendChatAction('typing').catch(() => {});
    
    const cleanText = text.replace(`@${ctx.botInfo.username}`, '').trim();
    const aiResponse = await callSupremeAI(cleanText);
    const senderAdmin = await isAuthorized(ctx, ctx.from.id);

    // --- BRANCH A: COMMAND EXECUTION ---
    if (aiResponse.includes('[') && aiResponse.includes('|') && aiResponse.includes('||')) {
        if (!senderAdmin) {
            return ctx.reply(`<b>SYSTEM ALERT</b>\nClearance denied.${DEVELOPER_TAG}`, { parse_mode: 'HTML', reply_to_message_id: ctx.message.message_id }).catch(() => {});
        }

        const [meta, uiMsg] = aiResponse.split('||');
        // V12 UPDATE: Triple split to extract Target ID generated by AI
        const [action, param, aiTargetId] = meta.replace('[', '').replace(']', '').split('|');
        
        const act = action.trim();
        const val = param ? param.trim() : '0';
        let finalTargetId = null;
        let targetMessage = null;

        // V12 Targeting Logic: ID inside text vs Reply
        if (aiTargetId && aiTargetId !== 'REPLY' && !isNaN(aiTargetId)) {
            finalTargetId = parseInt(aiTargetId.trim());
        } else if (isReply) {
            finalTargetId = isReply.from.id;
            targetMessage = isReply;
        }

        if (!finalTargetId) {
            return ctx.reply(`<b>SYSTEM ALERT</b>\nTarget missing. You must reply to a message OR provide a numeric User ID in your command.${DEVELOPER_TAG}`, { parse_mode: 'HTML', reply_to_message_id: ctx.message.message_id }).catch(() => {});
        }

        const targetAdmin = await isAuthorized(ctx, finalTargetId);

        // Admin Protection Matrix
        if (targetAdmin && ['BAN', 'KICK', 'MUTE', 'DEMOTE', 'WARN', 'PURGE', 'RESTRICT_MEDIA'].includes(act)) {
            return ctx.reply(`<b>MATRIX OVERRIDE</b>\nTarget holds Admin clearance. Directive nullified.${DEVELOPER_TAG}`, { parse_mode: 'HTML', reply_to_message_id: ctx.message.message_id }).catch(() => {});
        }

        try {
            const until = parseInt(val) > 0 ? Math.floor(Date.now() / 1000) + parseInt(val) : 0;

            switch (act) {
                case 'BAN': await ctx.banChatMember(finalTargetId); break;
                case 'KICK': await ctx.banChatMember(finalTargetId); await ctx.unbanChatMember(finalTargetId); break;
                case 'MUTE': await ctx.restrictChatMember(finalTargetId, { can_send_messages: false }, until > 0 ? { until_date: until } : {}); break;
                case 'UNMUTE': await ctx.restrictChatMember(finalTargetId, { can_send_messages: true, can_send_media_messages: true, can_send_other_messages: true, can_add_web_page_previews: true }); break;
                case 'PROMOTE': await ctx.promoteChatMember(finalTargetId, { can_change_info: true, can_delete_messages: true, can_invite_users: true, can_restrict_members: true, can_pin_messages: true, can_manage_video_chats: true }); break;
                case 'DEMOTE': await ctx.promoteChatMember(finalTargetId, { can_change_info: false, can_delete_messages: false, can_invite_users: false, can_restrict_members: false, can_pin_messages: false, can_manage_video_chats: false }); break;
                case 'WARN': break; 
                case 'RESTRICT_MEDIA': await ctx.restrictChatMember(finalTargetId, { can_send_messages: true, can_send_media_messages: false, can_send_other_messages: false, can_add_web_page_previews: false }, until > 0 ? { until_date: until } : {}); break;
                case 'TITLE': await ctx.setChatAdministratorCustomTitle(finalTargetId, val); break;
                // Actions requiring specific message IDs
                case 'DELETE': 
                    if (targetMessage) await ctx.deleteMessage(targetMessage.message_id); 
                    break;
                case 'PIN': 
                    if (targetMessage) await ctx.pinChatMessage(targetMessage.message_id); 
                    break;
                case 'UNPIN': 
                    if (targetMessage) await ctx.unpinChatMessage(targetMessage.message_id); 
                    break;
                case 'PURGE': 
                    if (targetMessage) await ctx.deleteMessage(targetMessage.message_id); 
                    await ctx.banChatMember(finalTargetId); 
                    break;
            }

            return ctx.reply(`${uiMsg.trim()}${DEVELOPER_TAG}`, { parse_mode: 'HTML', reply_to_message_id: ctx.message.message_id }).catch(() => {});

        } catch (err) {
            return ctx.reply(`<b>SYSTEM ERROR</b>\nExecution failed. Verify bot ranking and permissions.\n(Note: User ID must exist in group)${DEVELOPER_TAG}`, { parse_mode: 'HTML', reply_to_message_id: ctx.message.message_id }).catch(() => {});
        }
    }

    // --- BRANCH B: Q&A ---
    return ctx.reply(`${aiResponse.trim()}${DEVELOPER_TAG}`, { parse_mode: 'HTML', reply_to_message_id: ctx.message.message_id }).catch(() => {});
});

// ==========================================
// 6. SERVERLESS WEBHOOK HANDLER
// ==========================================
module.exports = async (req, res) => {
    try {
        if (req.method === 'POST') {
            const updateId = req.body.update_id;
            if (updateId) {
                if (processedUpdates.has(updateId)) return res.status(200).send('OK'); 
                processedUpdates.add(updateId);
                if (processedUpdates.size > 500) processedUpdates.clear();
            }
            await bot.handleUpdate(req.body);
            return res.status(200).send('OK');
        }
        res.status(200).send('OVERLORD V12 is Online.');
    } catch (e) {
        return res.status(200).send('OK');
    }
};
